# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9aeaca87a6955e4f86fbba9160b7a44fdab914c4449cb96b8ab25b7d7e207ab86aa3332baf4fb111f72c04b6f88b33416e7bf21579f34581d07cc1722a50092

test:
  secret_key_base: 3f714e9925fd11459940dd872e29aa9fd985b94173fedade05e8858e393784fdfdace09775f09159191e08d98a914afaf7ea43a5131b9fde464e0f8e065b7222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
